[package]
name = "pith-bin"
version = "1.0.0"
authors = ["ZippyMagician <zippymagician1@gmail.com>"]
edition = "2018"

[[bin]]
name = "pith"
path = "src/main.rs"

[dependencies]
pith-lib = { path = "../pith-lib" }
clap = "2.33.3"