[package]
name = "pith-bin"
version = "0.1.0"
authors = ["ZippyMagician <zippymagician1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pith-lib = { path = "../pith-lib" }